### ISSUE TITLE
大佬，请问这个脚本怎么用？都需要改哪里？

### ISSUE THREAD

**Issue by chengxue2020** [celetor/tvbox-build#1]
大佬，请问这个脚本怎么用？都需要改哪里？兰奏的Ylogin 和 phpdisk_info都填写了，LOCAL_XWALK不知道怎么填。要回国了，提前做好不能登录Github的准备，望指导一下，谢谢。

**Comment by celetor** [comment]
fork后啥都不用填，会自动编译发布的。要用蓝奏就把那两个环境变量填一下，LOCAL_XWALK不用填

**Comment by chengxue2020** [comment]
谢谢大佬的解答，还是没成功推送的兰奏，脚本这里是不是需要改一下啊？local_xwalk: ${{ secrets.LOCAL_XWALK }}
