### ISSUE TITLE
关于上传蓝揍云

### ISSUE THREAD

**Issue by ixinshang** [celetor/tvbox-build#2]
你好，工程文件运行正常。
现在遇到一个问题，我去掉了“- name: Commit And Push”这一部分，直接上传到蓝奏云。  
每次在actions之后，都会向蓝揍云上传一个apk（就是源码没有变化），导致蓝奏云出现2个名字完全一样的apk。

请教一下，这个情况怎么处理呢

**Comment by celetor** [comment]
> 你好，工程文件运行正常。 现在遇到一个问题，我去掉了“- name: Commit And Push”这一部分，直接上传到蓝奏云。 每次在actions之后，都会向蓝揍云上传一个apk（就是源码没有变化），导致蓝奏云出现2个名字完全一样的apk。
> 
> 请教一下，这个情况怎么处理呢
是根据Commit And Push提交的内容来判断目标仓库是否有新的代码上传的，没有这步判断结果永远都一样
